#!/usr/bin/env bash
set -e

REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")

while read -r local_ref local_sha remote_ref remote_sha
do
  if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
    continue
  fi

  RANGE="$remote_sha..$local_sha"

  if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
    RANGE="$local_sha"
  fi

  for commit in $(git rev-list "$RANGE"); do
    if ! git verify-commit "$commit" >/dev/null 2>&1; then
      echo "❌ Veuillez signer vos commits avant d'intéragir avec le repo ($REPO_NAME)"
      exit 1
    fi
  done
done
