import { config } from 'dotenv';
import { writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const adminRoot = resolve(scriptDir, '..');
const repoRoot = resolve(adminRoot, '..');
const envPath = resolve(repoRoot, '.env');

config({ path: envPath });

function escapeTsString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const appTitle = process.env.APP_TITLE?.trim() || 'Portfolio';
const apiUrl = process.env.ADMIN_API_URL?.trim() || '/api';

const content = `// Generated by scripts/sync-env.mjs - do not edit manually.
// Source: ${envPath.replace(/\\/g, '/')}
export const environment = {
  apiUrl: '${escapeTsString(apiUrl)}',
  appTitle: '${escapeTsString(appTitle)}',
} as const;
`;

for (const file of ['environment.ts', 'environment.prod.ts']) {
  writeFileSync(resolve(adminRoot, 'src/environments', file), content);
}

console.log(`[sync-env] Loaded ${envPath}`);
console.log(`[sync-env] appTitle="${appTitle}" apiUrl="${apiUrl}"`);
