// Generated by scripts/sync-env.mjs - do not edit manually.
// Source: C:/Users/willy/Documents/dev/portfolio/.env
export const environment = {
  apiUrl: '/api',
  appTitle: 'PHANG Willy',
} as const;
