import { Provider } from '@angular/core';
import { provideIcons } from '@ng-icons/core';
import {
  lucideArrowDown,
  lucideArrowUp,
  lucideArrowUpDown,
  lucideCheck,
  lucideCheckCircle,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsLeft,
  lucideChevronsRight,
  lucideCode,
  lucideEye,
  lucideEyeOff,
  lucideFolder,
  lucideHouse,
  lucideInbox,
  lucideKey,
  lucideLoader2,
  lucideLock,
  lucideLockOpen,
  lucideLogIn,
  lucideLogOut,
  lucideMail,
  lucideMenu,
  lucideMonitor,
  lucideMoon,
  lucidePanelLeftClose,
  lucidePencil,
  lucidePlus,
  lucideServer,
  lucideShield,
  lucideSearch,
  lucideSun,
  lucideTrash2,
  lucideUserPlus,
  lucideX,
} from '@ng-icons/lucide';

export const ADMIN_ICONS = {
  lucideArrowDown,
  lucideArrowUp,
  lucideArrowUpDown,
  lucideCheck,
  lucideCheckCircle,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsLeft,
  lucideChevronsRight,
  lucideCode,
  lucideEye,
  lucideEyeOff,
  lucideFolder,
  lucideHouse,
  lucideInbox,
  lucideKey,
  lucideLoader2,
  lucideLock,
  lucideLockOpen,
  lucideLogIn,
  lucideLogOut,
  lucideMail,
  lucideMenu,
  lucideMonitor,
  lucideMoon,
  lucidePanelLeftClose,
  lucidePencil,
  lucidePlus,
  lucideServer,
  lucideShield,
  lucideSearch,
  lucideSun,
  lucideTrash2,
  lucideUserPlus,
  lucideX,
} as const;

export function provideAdminIcons(): Provider {
  return provideIcons(ADMIN_ICONS);
}
