name: Branch name check

on:
  pull_request:
    branches:
      - dev
      - pre-prod
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^(dev|pre-prod|main)$ ]]; then
            echo "Main branch OK"
          elif [[ "$BRANCH_NAME" =~ ^(feat|fix|chore|docs|refactor|remove)/[a-z0-9._-]+$ ]]; then
            echo "Branch name OK"
          else
            echo "Invalid branch name. Use feat/... or fix/... or chore/... or docs/... or refactor/... or remove/..."
            exit 1
          fi
